{
    "updates": [
        {
            "directory": "/",
            "package-ecosystem": "elm",
            "schedule": {
                "interval": "daily"
            }
        },
        {
            "directory": "/review",
            "package-ecosystem": "elm",
            "schedule": {
                "interval": "daily"
            }
        },
        {
            "directory": "/",
            "package-ecosystem": "github-actions",
            "schedule": {
                "interval": "daily"
            }
        },
        {
            "directory": "/",
            "package-ecosystem": "npm",
            "schedule": {
                "interval": "daily"
            }
        }
    ],
    "version": 2
}
